Repository WillyJL/F95Checker, pull requests merged in 2024-11, with the labels that each got.

#180 F95Indexer: Cache API for F95Checker
  .github/workflows/build.yml
  .gitignore
  README.md
  browser/.prettierrc
  browser/chrome.zip
  browser/chrome/extension.js
  browser/chrome/icons/128.png
  browser/chrome/icons/16.png
  browser/chrome/icons/32.png
  browser/chrome/icons/64.png
  browser/chrome/manifest.json
  browser/firefox.zip
  browser/firefox/extension.js
  browser/firefox/icons/128.png
  browser/firefox/icons/16.png
  browser/firefox/icons/32.png
  browser/firefox/icons/64.png
  browser/firefox/manifest.json
  browser/integrated.js
  common/parser.py
  common/structs.py
  external/async_thread.py
  external/error.py
  external/filepicker.py
  external/imagehelper.py
  external/ratingwidget.py
  external/singleton.py
  external/sync_thread.py
  external/ziparch.py
  indexer-main.py
  indexer.env-example
  indexer/cache.py
  indexer/f95zone.py
  indexer/scraper.py
  indexer/threads.py
  indexer/watcher.py
  main.py
  modules/api.py
  modules/callbacks.py
  modules/db.py
  modules/globals.py
  modules/gui.py
  modules/icons.py
  modules/msgbox.py
  modules/rpc_thread.py
  modules/rpdl.py
  modules/utils.py
  modules/webview.py
  requirements-indexer.txt
  requirements.txt
  setup.py
  tags-diff.py
Labels: bugfix

#170 Skip/force refresh for completed/archived games
  common/structs.py
  modules/api.py
  modules/db.py
  modules/gui.py
Labels: enhancement

#184 Api robustness
  indexer/cache.py
  indexer/f95zone.py
  indexer/scraper.py
  indexer/watcher.py
Labels: bugfix

#188 Improve reliability of latest updates watcher
  indexer/watcher.py
Labels: bugfix

#187 Unmasked downloads with Cache API
  common/parser.py
  indexer/f95zone.py
  indexer/scraper.py
  modules/api.py
  modules/callbacks.py
  modules/gui.py
  modules/webview.py
Labels: bugfix

#182 Fix Wayland issues
  modules/globals.py
  requirements.txt
Labels: bugfix

#190 F95zone Donor DDL
  common/structs.py
  indexer/f95zone.py
  indexer/scraper.py
  modules/api.py
  modules/db.py
  modules/gui.py
Labels: feature
